-- migrate:up
CREATE TABLE orders (
    id INT NOT NULLAUTO_INCREMENT PRIMARY KEY,
    order_number VARCHAR NOT NULL,
    user_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    adress VARCHAR(50) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    email VARCHAR(50) NULL,
    orders_status_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- migrate:down
DROP TABLE orders;